BRIKEV/express-jsdoc-swagger

- test/transforms/components/index.test.js
- transforms/components/index.js
- transforms/paths/index.js
- transforms/utils/tags.js
> Components transform

- index.js
- test/transforms/components/index.test.js
- transforms/components/index.js
- transforms/index.js
- transforms/paths/index.js
- transforms/utils/validateTypes.js
Added reference between two jsdoc components.
> Components refs

- test/transforms/paths/responses.test.js
- transforms/components/index.js
- transforms/paths/schema.js
- transforms/utils/refSchema.js
- transforms/utils/validateTypes.js
This PR includes references to components in the response tags.
> Response references

- index.js
- transforms/index.js
@bri06 this is how we are adding the transform to our real scenario.
> feat: add tags to e2e method

- test/transforms/paths/index.test.js
- test/transforms/paths/parameters.test.js
- test/transforms/paths/requestBody.test.js
- test/transforms/paths/responses.test.js
- test/transforms/paths/tags.test.js
- transforms/paths/index.js
This PR includes new feature for each option. The possibility of desecrating endpoints by adding.
```
* @deprecated
```
> feat: add deprecated option for each endpoint

- consumers/jsdocInfo.js
- test/transforms/paths/index.test.js
- test/transforms/paths/requestBody.test.js
- transforms/paths/index.js
- transforms/paths/requestBody.js
This PR adds a test for multiple endpoints and multiple methods for the same endpoints. It also includes a fix for empty body params.
> Multiple endpoints

- .eslintignore
- examples/README.md
- examples/basic/index.js
- examples/configuration/main.js
- examples/package-lock.json
- examples/package.json
- examples/responses/components.js
- examples/responses/full-example.js
- examples/responses/multiple.js
- examples/responses/simple.js
- examples/utils/logger.js
- index.js
- test/transforms/basic/index.test.js
- test/transforms/components/index.test.js
- test/transforms/tags/index.test.js
- transforms/basic/servers.js
- transforms/components/index.js
- transforms/paths/responses.js
- transforms/tags/index.js
- transforms/utils/setProperty.js
This PR includes the first version of the examples folder.
> More examples

- .github/workflows/npm-publish.yml
- README.md
Improve CI script to execute tests in more than one node version.
> ci: add more node versions

- commitlint.config.js
- package-lock.json
- package.json
This PR includes:
- Commitlint: conventional configuration
> Commitlint

- transforms/paths/parameters.js
This PR includes a refactor in parseParameter method to fix this code climate [issue](https://codeclimate.com/github/BRIKEV/express-jsdoc-swagger/transforms/paths/parameters.js/source#issue-3304101220da45cd188e5e24fb3c8404).
> [refactor] max line function code smell

- examples/README.md
- examples/package.json
- examples/security/basic-auth.js
- index.js
- test/transforms/security/index.test.js
- transforms/components/index.js
- transforms/index.js
- transforms/security/index.js
This PR contains:
- security section.
- securitySchemes within components with the name of each security scheme.
> Security schemes

- transforms/paths/responses.js
This PR fixes codeclimate issue:
- Function responsesGenerator has a Cognitive Complexity of 7
> [refactor]: responsesGenerator method in paths transforms

- examples/README.md
- examples/components/simple.js
- examples/package.json
- test/transforms/components/index.test.js
- transforms/components/index.js
This PR includes: 
- Components examples.
- Tested more component options.
> Components examples

- examples/README.md
- examples/package.json
- examples/tags/simple.js
- test/transforms/paths/tags.test.js
- test/transforms/tags/index.test.js
- transforms/paths/index.js
- transforms/tags/index.js
- transforms/utils/tags.js
- Added tags example.
- Added more tags test.
- Refactor of tags methods.
- Added funtionality to sort tags by name.
> Tags examples

- transforms/paths/index.js
> refactor: move path values to a different function

- examples/README.md
- examples/package.json
- examples/requestBody/components.js
- examples/requestBody/multiple.js
- examples/requestBody/simple.js
- test/transforms/paths/requestBody.test.js
- transforms/components/index.js
- transforms/utils/mapDescription.js
This PR includes one fix for description mapping when there is no value, and documentation for request body. This closes #26
> Docs request body

- index.js
- processSwagger.js
- test/e2e/components/components.test.js
- test/e2e/components/jsdoc-example.js
- test/e2e/configuration/configuration.test.js
- test/e2e/parameters/jsdoc-example.js
- test/e2e/parameters/parameters.test.js
- transforms/paths/index.js
- transforms/utils/httpMethods.js
This PR adds a refator of the main function to separate all the swagger parse process in another file so that it will be easier to tests all the e2e features. This also should close #29.
It also includes a fix when we create the paths as there wasn't a validation if it was an endpoint or not.
I added some e2e tests but it still needs more, but I will address those in another PR.
> Refactor main function

- transforms/paths/index.js
> refactor: parsePaths method

- transforms/paths/responses.js
> refactor: responsesGenerator method

- examples/configuration/main.js
- index.js
- package-lock.json
- package.json
> Merge option

- examples/README.md
- examples/configuration/main.js
- examples/merge/simple.js
- examples/merge/swagger.js
- examples/package.json
This PR includes the creation of a specific file for merge option example.
> Merge example

- README.md
- index.js
This PR includes swaggerUIPath option to customize the URL where the Swager UI will be rendered.
> feat: added swaggerUIPath option

- examples/README.md
- examples/combineSchemas/index.js
- examples/package.json
- test/transforms/paths/combineSchemas.test.js
- transforms/components/index.js
- transforms/paths/schema.js
- transforms/utils/combineSchema.js
This PR closes #36 
It still has some corner cases but I think those should be addressed with the merge feature.
> Combine request feature

- examples/package.json
- examples/requestBody/formdata.js
This PR includes a form-data requestBody example
> docs: add form-data example

- consumers/globFilesMatches.js
- test/consumers/globFilesMatches/index.test.js
- test/consumers/readFiles/index.test.js
This PR adds some tests and improve coverage in utils folder.
> feat: improve utils coverage

- examples/components/simple.js
- test/transforms/components/index.test.js
- transforms/components/index.js
This PR includes: 
- Fixed components schema when it has a property with an array of string/number
> Components array

- examples/responses/full-example.js
- transforms/components/index.js
- transforms/utils/enumValues.js
> Format properties complexity

- test/e2e/errors/errors.test.js
- test/e2e/errors/jsdoc-parameter-error.js
- test/e2e/errors/jsdoc-requestBody-error.js
- test/e2e/errors/jsdoc-response-error.js
- transforms/paths/content.js
- transforms/paths/parameters.js
- transforms/paths/requestBody.js
- transforms/paths/responses.js
- transforms/paths/schema.js
This PR includes a better error messaging for incomplete wrong params and wrong requestBody params.
This closes #64
> Improve error messages

- examples/components/simple.js
- test/transforms/components/index.test.js
- transforms/components/index.js
- transforms/paths/schema.js
- transforms/utils/combineSchema.js
- transforms/utils/refSchema.js
> Components array refs

- README.md
- examples/combineSchemas/index.js
- examples/components/enum.js
- examples/components/simple.js
- examples/merge/simple.js
- examples/parameters/components.js
- examples/parameters/multiple.js
- examples/requestBody/components.js
- examples/requestBody/formdata.js
- examples/requestBody/multiple.js
- examples/requestBody/simple.js
- examples/responses/components.js
- examples/tags/simple.js
- test/e2e/parameters/parameters.test.js
- test/transforms/paths/combineSchemas.test.js
- test/transforms/paths/parameters.test.js
- transforms/paths/parameters.js
This PR includes:
- Docs improvement (Some errors after using openapi-enforcer validator)
- Remove `allowEmptyValue`  support. This tag will be removed in future versions. 
This closes #68
> Enforcer validation

- README.md
- package.json
- test/e2e/errors/errors.test.js
- transforms/paths/parameters.js
- transforms/paths/responses.js
- transforms/paths/schema.js
- transforms/utils/combineSchema.js
- transforms/utils/errorMessage.js
- transforms/utils/setProperty.js
This PR includes better error messages and new README and package.json description. Please have a look and confirm if it is okay to have that description.
> Refactor error messages

- consumers/globFilesMatches.js
This PR closes #74 
It was a problem with glob dependency and not with the way we process our files. However, I will keep the work of this [branch](https://github.com/BRIKEV/express-jsdoc-swagger/tree/fix-processor) so that we can refactor that.
> fix: memory problem

- test/e2e/components/components.test.js
- test/e2e/components/jsdoc-example.js
- test/e2e/parameters/jsdoc-example.js
- test/e2e/parameters/parameters.test.js
- test/transforms/basic/index.test.js
- transforms/basic/info.js
- transforms/basic/servers.js
> Validators

- test/e2e/components/components.test.js
- test/transforms/components/index.test.js
- test/transforms/paths/combineSchemas.test.js
- transforms/components/index.js
> Required properties

- package.json
This PR includes new package version release.
> chore: update package json release

- package-lock.json
- package.json
Commitlint security error in dependency fixed.
> chore: update commitlint dependency

- examples/package.json
- examples/requestBody/formUrlencoded.js
- test/transforms/paths/requestBody.test.js
This PR adds documentation for `application/x-www-form-urlencoded`.
This is related to this issue #86
> docs: add new request body example

- examples/package.json
- examples/parameters/headers.js
This PR adds an example of request headers. This example was requested in a private slack channel 👍
> docs: add header param example

- package-lock.json
- transforms/paths/requestBody.js
Small refactor to avoid long methods
> Extract examples validator value as function - long methods

- transforms/paths/formParams.js
Small refactor in formParams to avoit long methods and side effects.
> Refactor formParams

- .github/workflows/runTests.yml
- examples/responses/withExamples.js
- test/transforms/paths/responses.test.js
- transforms/paths/examples.js
- transforms/paths/parameters.js
- transforms/paths/requestBody.js
- transforms/utils/generator.js
This PR fixes:
- Duplication issue of [code climate](https://codeclimate.com/github/BRIKEV/express-jsdoc-swagger/issues?category=duplication&engine_name%5B%5D=structure&engine_name%5B%5D=duplication)
- Code smell of [code climate](https://codeclimate.com/github/BRIKEV/express-jsdoc-swagger/issues?category=complexity&engine_name%5B%5D=structure&engine_name%5B%5D=duplication)
> Fix codeclimate

- .eslintrc.json
- consumers/utils/getComments.js
- test/e2e/components/jsdoc-example.js
- test/e2e/errors/jsdoc-parameter-error.js
- test/e2e/errors/jsdoc-requestBody-error.js
- test/e2e/errors/jsdoc-response-error.js
- test/transforms/paths/responses.test.js
- transforms/components/index.js
- transforms/paths/responses.js
- transforms/paths/validStatusCodes.js
- transforms/security/index.js
- transforms/utils/arrays.js
- transforms/utils/enumValues.js
- transforms/utils/httpMethods.js
- transforms/utils/mapDescription.js
I try to parse the response example in case it's content type is "application/json".
> feat: try to convert json string to object for response example tags

- .eslintrc.json
- examples/responses/withExamples.js
- test/transforms/paths/responses.test.js
- transforms/paths/responses.js
This PR includes:
- Examples format test.
- Fix example file of OpenAPI responses with examples.
- Remove catch linter rule.
> Example error message

- examples/ts-example/simple.ts
- index.d.ts
This PR closes #123. There were some errors with the TS types in the server definition and also in the security definitions. 
We also update the Docs.
> fix: ts types error for security type

- index.d.ts
- index.js
Adds a new key swaggerUiOptions to Options object so that options can be passed to swaggerUi.
> feat: add swaggerUi options

- index.js
> fix: remove host option from export swagger docs

- examples/package.json
- examples/security/basic-oauth2.js
- examples/security/swagger.json
This PR is an example of a workaround for adding Oauth2 security. This is related to this issue #170. It does not solve the issue but this is a workaround.
> docs: add oauth2 security example

- .github/workflows/npm-publish.yml
- .github/workflows/runTests.yml
- package-lock.json
- package.json
- test/consumers/globFilesMatches/index.test.js
This PR fixes an issue with one test and updates the dependencies that have vulnerabilities.
> fix: update tests and dependencies
