- consumers/utils/getComments.js
- test/consumers/getOnlyComments/index.test.js
This PR fixes a problem when there is code before the comment and the comment has spaces or tabs.
> fix: only comment regex

- test/transforms/components/index.test.js
- transforms/components/index.js
For parameters and return types we can combine schemas with `allOf`, `oneOf`, `anyOf`.
I thought we should be able to use them for schema definition (`@typedef`)
> Allow combining schemas on typedef 

- README.md
- examples/package.json
- examples/requestBody/withExample.js
- examples/requestBody/withExamples.js
- examples/responses/withExamples.js
- test/transforms/paths/requestBody.test.js
- test/transforms/paths/responses.test.js
- transforms/paths/content.js
- transforms/paths/examples.js
- transforms/paths/index.js
- transforms/paths/requestBody.js
- transforms/paths/responses.js
- ~Bugfix~
- Feature
- Test
- Docs
- ~Refactor~
- Build-related changes
- ~Other, please describe:~
This PR adds support for `@example` annotations. These can be used to add examples on the expected input / output for every endpoint of our API. More details on its usage and specifications can be found in the sections listed below.
Should close #89.
The following example illustrates how the `@example` annotation can be used to add examples on how the request body must be, as well as what the endpoint is supposed to return for specific status codes.
```javascript
/**
* POST /api/v1/song
* @param {Song} request.body.required - song info
* @return {object} 200 - song response
* @return {object} 400 - Bad request response
* @example request - example payload
* {
*   "title": "untitled song",
* …
```
> feat: add support for `example` annotations

- examples/package.json
- examples/requestBody/formParameters.js
- package.json
- test/transforms/paths/formParameters.test.js
- transforms/paths/content.js
- transforms/paths/formParams.js
- transforms/paths/index.js
- transforms/paths/parameters.js
- transforms/paths/requestBody.js
This PR includes the feature of using only `.form` values for a request body instead of creating a model for each endpoint.
The definition is like this:
```
/**
* POST /api/v1/song
* @param {string} id.form.required - This is the song id - application/x-www-form-urlencoded
* @param {string} title.form.required - This is the song title - application/x-www-form-urlencoded
* @return {object} 200 - song response
*/
```
Where we use
```
* @param {string} [key].form.[!required] - [Description] - [content type]
```
This closes #86
> Form parameters

- README.md
- consumers/globFilesMatches.js
- index.d.ts
- test/consumers/globFilesMatches/index.test.js
Adds support for passing multiple file patterns to `options.filesPattern`. Addresses #101
> Allow passing multiple file patterns

- index.d.ts
- index.js
Stays fully backwards compatible.
Added the option to decide whether to expose swagger-ui and api-docs. They can be enabled/disabled separately. Swagger UI is enabled by default to stay backwards compatible. This is the same reason api-docs exposure is disabled by default, because there could be projects, that use `/v3/api-docs` already. 
I would suggest a change in the default swagger ui path though if there will be a major version update, cause the recommended path by swagger is /swagger-ui/index.html or /swagger-ui/. 
This PR would close #114.
> Added options to expose swagger-ui or api-docs separately

- examples/configuration/multipleInstance.js
- examples/eventEmitter/multipleInstance.js
- index.js
doc: add example in configuration -> multipleInstance
doc: add example in eventEmitter -> multipleInstance
It was impossible to create several instances because of the variable
"instance" to instantiate globally and not for the current swagger.
Instance verification condition, blocked the creation of another swagger
The creation of a new instance was blocked.
Ability to create multiple swagger instances with their own swaggerEvents.
I added examples of multiple instance in the configuration and eventEmitter folder
> feat: update swagger events for only current instance

- .gitignore
- package-lock.json
- package.json
- test/transforms/paths/combineSchemas.test.js
- test/transforms/paths/responses.test.js
- transforms/paths/schema.js
- transforms/utils/combineSchema.js
- transforms/utils/refSchema.js
Update packages to latest version, no breaking changes.
Ability to describe response as array of different schema example:
```
/**
* GET /api/v1
* @summary This is the summary or description of the endpoint
* @return {array<Song|Album>} 200 - success response - application/json
*/
// this allow you to have schema that match this response
res.json( [ {songId:1} , {songId:2} , {AlbumId:3} ] )
```
Ability to describe property as array of different schemas, example: 
```
/**
* Album
* @typedef {object} Album
* @property {anyOf|Song[]|Album|string|string[]} firstSong
*/
```
Convert  Null to {} in swagger
> Feature: support 2 new syntax for array of schema in @return and in @property

- README.md
- examples/combineSchemas/index.js
- examples/configuration/main.js
- examples/configuration/multiple-files.txt
- examples/configuration/multipleFiles.js
- examples/configuration/multipleInstance/admin-v1-docs.js
- examples/configuration/multipleInstance/client-v1-docs.js
- examples/merge/simple.js
- examples/parameters/components.js
- examples/parameters/enum.js
- examples/parameters/headers.js
- examples/parameters/multiple.js
- examples/parameters/simple.js
- examples/responses/components.js
- examples/responses/full-example.js
- examples/responses/multiple.js
- examples/responses/simple.js
- examples/security/basic-auth.js
- examples/ts-example/simple.ts
- test/e2e/errors/jsdoc-parameter-error.js
- test/e2e/errors/jsdoc-requestBody-error.js
- test/e2e/errors/jsdoc-response-error.js
- test/e2e/parameters/jsdoc-example.js
- test/e2e/parameters/parameters.test.js
- test/transforms/paths/combineSchemas.test.js
- test/transforms/paths/index.test.js
- test/transforms/paths/responses.test.js
- transforms/paths/index.js
Adds support for the `@description` tag so that you can provide longer descriptions for API endpoints while summarizing with the `@summary` tag. Adapted one of the tests to have a simple verification and ran a global-replace of `summary or description` => `summary` which resulted in quite a diff. 
_Offtopic: A big thanks to everyone contributing here by the way, we're using `express-jsdoc-swagger` to generate OpenAPI specs that a Node process writes to a file that in turn Redocly uses to display it within a documentation portal 🙌 Like the way it's made to be a good fit for REST APIs while still adhering to the JSDoc standards_
> feat: Added parsing of JSDoc @description tags

- examples/nullableFields/index.js
- test/transforms/paths/combineSchemas.test.js
- transforms/utils/combineSchema.js
When parsing properties with multiple data types, there was an issue if the user did not add one of the Swagger keywords (`oneOf`, `anyOf` or `allOf`) as the first item in the list, for example:
```
/**
* @typedef {object} Song
* @property {string} title.required
* @property {string} artist
* @property {number} year
* @property {object|number} releaseDate
*/
```
In this scenario, the generated schema for the `releaseDate` property would only contain the second type:
```
{
'description': '',
'type': 'number',
}
```
As the library assumed the first item to be a keyword and not a real type, the `object` type would be completely ignored and not appear into the generated schema. 
This PR fixes this issue, making the usage of `oneOf`, `anyOf` or `allOf` keywords optional. If the user chooses to …
> fix: multiple data types without swagger keywords

- README.md
- config/default.js
- examples/nullableFields/explicitNullable.js
- examples/nullableFields/nullableByDefault.js
- examples/package.json
- index.d.ts
- index.js
- processSwagger.js
- test/transforms/components/index.test.js
- transforms/components/index.js
- transforms/utils/combineSchema.js
This PR introduces a new option to the library's configuration object, `notRequiredAsNullable`. This will allow users to **configure whether non-required props shall be interpreted as `nullable` or not**. To maintain the current behaviour, this setting will be disabled by default. 
Currently, a required property is just expected not to be `undefined` in our request or response payload. Thus, we're considering `null` as an actual value for a property. For this, we're working under the assumption that **the meaning of `undefined` and `null` is different**:
- `null` represents an explicit empty value.
- `undefined` means that we have no idea of the real value of that property. It could either be empty, or not. 
Let's better illustrate the difference with an example:
```
/**
* @typedef …
```
> feat: make optional properties nullable by default

- transforms/utils/combineSchema.js
This feature removes the warning message as we are providing support to multiple types with this notation `{string|null}`. We don't need to warn about using `anyOf`, `oneOf` or any OpenAPI reserved word.
> feat: remove warning with different types

- test/transforms/paths/responses.test.js
- transforms/paths/index.js
JSDocs provides a [`@returns` tag](https://jsdoc.app/tags-returns.html) with the same meaning as `@return`. This PR adds support to this tag, so both `@return` and `@returns` can be used to document the output of an endpoint.
> feat: add support for `@returns` tag

- README.md
This PR includes `express-oas-validator` example in the readme so that people can use the advantages of this package mixed with the `express-jsdoc-swagger`.
> docs: update readme with validator example

- test/transforms/paths/requestBody.test.js
- transforms/utils/httpMethods.js
- Bugfix
- ~Feature~
- Test
- ~Docs~
- ~Refactor~
- ~Build-related changes~
As mentioned in [this link](https://stackoverflow.com/a/10015724/12911174) or in the [official docs for the DELETE method in HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE), this request type should be able to receive a body. 
This PR modifies the `validRequestBodyMethods` configuration object so that `DELETE` methods are now considered eligible to have a request body, so the value `@param {x} request.body` in the endpoint comments will no longer be ignored when generating the Swagger docs.
Should fix #176.
> fix: add support to delete requests with body

- config/swaggerEvents.js
- index.js
- test/e2e/parameters/parameters.test.js
- test/transforms/paths/combineSchemas.test.js
- test/transforms/paths/formParameters.test.js
- test/transforms/paths/index.test.js
- test/transforms/paths/parameters.test.js
- test/transforms/paths/requestBody.test.js
- test/transforms/paths/responses.test.js
- test/transforms/paths/security.test.js
- test/transforms/paths/tags.test.js
- transforms/paths/content.js
- transforms/paths/requestBody.js
These tests broke. I'm not sure why only making a change in
transforms/paths/index.js under the parsePath response
triggers the failures.
Found it while making the changes for: https://github.com/BRIKEV/express-jsdoc-swagger/pull/179
> fix(test): test failed after making an unrelated change

- transforms/paths/parameters.js
> Add support for explode

- test/transforms/components/index.test.js
- transforms/components/index.js
This adds support for non-object typedefs such as string - previously it would emit an "object" type for non-object typedefs
> Add support for non-object typedefs

- test/transforms/components/index.test.js
- test/transforms/paths/parameters.test.js
- transforms/components/index.js
- transforms/paths/schema.js
Update logic for type application casing to ensure lowercase.
When types such as `Array<Song>` or `Song[]` are used, the `type` for the property resolves to `'Array'` rather than the officially support OpenAPI [data type](https://swagger.io/docs/specification/data-models/data-types/) of `'array'`. When the type is `'Array'`, the OpenAPI document does not correctly recognize the property as a valid array. The officially supported types are lowercase anyway:
- [string](https://swagger.io/docs/specification/data-models/data-types/#string) (this includes dates and [files](https://swagger.io/docs/specification/data-models/data-types/#file))
- [number](https://swagger.io/docs/specification/data-models/data-types/#numbers)
- [integer](https://swagger.io/docs/specification/data-models/data-types/# …
> fix: schema type casing

- test/transforms/components/index.test.js
- transforms/components/index.js
- [x ] Feature
This PR adds support for dictionaries with objects as values as described in the OpenAPI spec under "Value type" (second example here: https://swagger.io/docs/specification/data-models/dictionaries/
As my understanding of the codebase is limited I don't think the implementation is optimal but hopefully someone with more familiarity of the codebase can refactor it to a satisfactory level?
> feat: support for dictionaries

- .vscode/launch.json
- test/transforms/components/index.test.js
- transforms/components/index.js
Add support for using primitive values with `Dictionary` special type. For example to represent object with any number of string keys and string values:
```
{
"en": "English",
"fr": "French"
}
```
Official documentation on dictionaries in OpenAPI:
https://swagger.io/docs/specification/data-models/dictionaries/
While `object` is technically a primitive value based on `TYPES` in `transforms/utils/validateTypes.js`, users of this library will want to use `typedef` to represent objects.
For what it's worth, normally in JSDoc [dictionary/record](https://jsdoc.app/tags-type.html) type objects are represented as:
```
Object.<string,string>
```
> feat: add support for dictionary primitives
